# Generated by Django 3.2.6 on 2021-10-11 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0004_alter_person_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='hiker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hikes', to='stats_api.person'),
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/% Y/% m/% d/'),
        ),
    ]
