# Generated by Django 3.2.7 on 2021-10-12 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0007_alter_person_join_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.ImageField(blank=True, null=True, upload_to='static/images/%Y/%m/%d'),
        ),
    ]
