# Generated by Django 3.2.7 on 2021-10-27 01:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stats_api', '0008_alter_person_profile_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='slug',
            field=models.SlugField(default='fn-ln'),
            preserve_default=False,
        ),
    ]
