# Generated by Django 3.2.7 on 2021-09-27 21:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, null=True)),
                ('last_name', models.CharField(max_length=100, null=True)),
                ('birthdate', models.DateField(blank=True, max_length=100)),
                ('email', models.EmailField(max_length=100, null=True)),
                ('profile_img', models.ImageField(null=True, upload_to='uploads/% Y/% m/% d/')),
            ],
        ),
        migrations.CreateModel(
            name='Hike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hike_date', models.DateField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('state', models.CharField(blank=True, max_length=30)),
                ('distance', models.CharField(blank=True, max_length=20)),
                ('elevation_gain', models.IntegerField(blank=True, max_length=10)),
                ('highest_elev', models.IntegerField(blank=True, max_length=10)),
                ('alltrails_url', models.URLField(blank=True, max_length=100)),
                ('blogger_url', models.URLField(blank=True, max_length=100)),
                ('hiker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='person_hiker', to='api.person')),
            ],
        ),
    ]
