# Generated by Django 3.2.6 on 2021-10-10 19:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='person',
            old_name='birthdate',
            new_name='join_date',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='distance',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='elevation_gain',
        ),
        migrations.RemoveField(
            model_name='hike',
            name='highest_elev',
        ),
        migrations.AddField(
            model_name='hike',
            name='distance_mi',
            field=models.FloatField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='elevation_gain_ft',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hike',
            name='highest_elev_ft',
            field=models.IntegerField(blank=True, default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='email',
            field=models.EmailField(default='lmoiola@gmail.com', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(default='fn', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(default='ln', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='person',
            name='profile_img',
            field=models.ImageField(blank=True, default=0, upload_to='uploads/% Y/% m/% d/'),
            preserve_default=False,
        ),
    ]
