# Generated by Django 3.2.6 on 2021-10-10 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20211010_1226'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hike',
            name='alltrails_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='blogger_url',
            field=models.URLField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='distance_mi',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='hike',
            name='elevation_gain_ft',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='hike',
            name='highest_elev_ft',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hike',
            name='state',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='person',
            name='join_date',
            field=models.DateField(max_length=100),
        ),
    ]
